### ISSUE TITLE
MDBList Feature Request: Choose Instance

### ISSUE THREAD

**Issue by DrSeussFreak** [Notifiarr/website#256]
Right now, when I send a movie to radarr via mdblist, it goes to all instances of radarr I have running.  I would love a way to either choose an instance or select a single instance for all requests.

**Comment by austinwbest** [comment]
I can add a default instance picker, it just gets tricky because of all the other API calls for the starr info being done too. You wouldn't be able to pick which instance things go to, that would need to be done on the mdblist side but he mentioned awhile ago he had no desire to deal with multiple instance support so i left it at that.

**Comment by DrSeussFreak** [comment]
I had figured this was the case, that was why I added the last part of choosing a single instance.  This would work just fine for me, it would solve my problem.

**Comment by austinwbest** [comment]
This is next on the list as i have to add another feature for mdblist but linas is coming around to an instance picker on his side so there might be hope for it down the road

**Comment by DrSeussFreak** [comment]
Sounds good, thank you

**Comment by austinwbest** [comment]
Done on nightly
