### ISSUE TITLE
Service check interval doesn't change

### ISSUE THREAD

**Issue by ntegradryvr** [Notifiarr/website#40]
Default interval below was "10m0s", changed to 5m.  Seems as if the message in discord from the service check is checking the service _maybe every_ 5 minutes but only updating the discord post every 10m.

[services]
  disabled = false   # Setting this to true disables all service checking routines.
  parallel = 1       # How many services to check concurrently. 1 should be enough.
  interval = "5m0s" # How often to send service states to Notifiarr.com. Minimum = 5m.

**Comment by ntegradryvr** [comment]
![image](https://user-images.githubusercontent.com/22271387/124689031-66bfa700-de9d-11eb-928d-9d7699c5b6f1.png)

**Comment by davidnewhall** [comment]
This sounds like expected behavior. I think @austinwbest and I decided that a 10 minute update interval in Discord is appropriate while allowing you to check services a bit more often. This allows the "service up" and "service down" durations to be a bit more accurate while not flooding Discord with API hits for down services. I could be wrong, and he may have meant to make it 5 minutes.

**Comment by austinwbest** [comment]
The one on the conf is for the client only, yea & as David said checks more often for a more accurate downtime amount in the network notifications. The site and that status has its own cron which can't be that frequent as it gets hit by discord rate limiting on updating the existing message to many times in an hour. I found that out with hotio's version posts.
