### ISSUE TITLE
[Feature Request] Purge All Messages

### ISSUE THREAD

**Issue by jrdnlc** [Notifiarr/website#94]
Command that will allow us to purge all messages in a channel/s

**Comment by austinwbest** [comment]
> This endpoint will not delete messages older than 2 weeks, and will fail with a 400 BAD REQUEST if any message provided is older than that or if any duplicate message IDs are provided.

https://discord.com/developers/docs/resources/channel#bulk-delete-messages

Seems "all" might not be possible...

Edit: I am going to build the keyword either way and we will see what happens
Edit 2: So it seems that restriction is placed on the bulk delete only, the single message delete doesnt document that restriction.  So this will be a bulk call for everything newer than 2 weeks and then individual calls for older.
Edit 3: Doing some reading, it looks like other bots stop at the 2 week limit which makes sense because that can be rough trying to purge hundreds or thousands of messages one by one
